name: Sync to Hugging Face
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "kidbradaki1@gmail.com"
          git config --global user.name "ghost-analyst"
          # Força a reconfiguração do destino
          git remote add hf https://ghost-analyst:$HF_TOKEN@huggingface.co/spaces/ghost-analyst/central-ghost-bravo || git remote set-url hf https://ghost-analyst:$HF_TOKEN@huggingface.co/spaces/ghost-analyst/central-ghost-bravo
          # O comando '--force' é o que vence o erro vermelho
          git push hf main --force
